language: python
python:
  - "2.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# before_script:
script:
    - flake8 --ignore=E501,E302 . # ignore len > 79char; 2 blank lines after flask route
    # - python -m flake8 # test for linting
    # - python -m pytest -v