sudo: required
services:
    - docker
language: python
python:
#   - "2.7"
  - "3.8"
env:
    global:
      # Docker Hub cannot handle uppercase characters in repository names. Fix it
      # with a bashism as Travis CI cannot handle quoting within command
      # substitution.
      - LOWERCASE_REPO_SLUG="${TRAVIS_REPO_SLUG,,}"
# command to install dependencies
install:
  - pip install -r requirements.txt
# before_script:
script:
    - flake8 --ignore=E501,E302 . # ignore len > 79char; 2 blank lines after flask route
    # - python -m flake8 # test for linting
    # - python -m pytest -v
after_success:
    - sh .travis/deploy_dockerhub.sh