language: python
python:
  - "2.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
    - pytest --flake8
    # - python -m flake8 # test for linting
    # - python -m pytest -v